Project readme + function to create .lintr file
Appsilon/box.linters pull request #66
Opened 2024-05-17 05:13 UTC by radbasa

*Have you read the [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md)?*

Issue #62 

## Description
* Wrote the readme for the project
* Added a `use_box_lintr()` function patterned after `lintr::use_lintr()`.

## Definition of Done
- [ ] The change is thoroughly documented.
- [ ] The CI passes (`R CMD check`, linter, unit tests, spelling).
- [ ] Any generated files have been updated (e.g. `.Rd` files with `roxygen2::roxygenise()`)

2024-05-17 09:00 UTC, jakubnowicki requested changes
Please check my comments.

2024-05-17 09:00 UTC, jakubnowicki commented on R/use_box_lintr.R
> +  )
This will require keeping the `rhino` version the same as the one present in Rhino itself. Instead, I think a good idea would be to simply copy `inst/templates/app_structure/dot.lintr` from `rhino`. To add consistency, the basic box should be also stored as file in `box.linters` and copied (the file name `dot.lintr` instead of `.lintr` is a solution for building R package - it ignores dot files, so this is a workaround to make sure to include this file in the package).

2024-05-17 09:00 UTC, jakubnowicki commented on R/use_box_lintr.R
> +    stop("Found an existing configuration file at '", config_file, "'.", call. = FALSE)
Maybe instead of a hard stop, a question to overwrite (with a default No)?

2024-05-20 05:59 UTC, radbasa commented on R/use_box_lintr.R
> +  )
Done. Had to add a `default = ".lintr` because in my short and quick testing, "options()` did not contain `$lintr.linter_file`.

2024-05-20 05:59 UTC, radbasa commented on R/use_box_lintr.R
> +  )
Done, now copying `dot.lintr` files from packages to `.lintr`

2024-05-20 06:00 UTC, radbasa commented on R/use_box_lintr.R
> +    stop("Found an existing configuration file at '", config_file, "'.", call. = FALSE)
Done. Added quick and simple prompt.

2024-05-20 13:23 UTC, jakubnowicki approved these changes
LGTM

2024-05-21 03:17 UTC, merged