pkgdown setup
Appsilon/box.linters pull request #67
Opened 2024-05-17 08:52 UTC by radbasa

Issue #43

## Description
* set up `pkgdown`. ready for vignettes.

## Definition of Done
- [ ] The change is thoroughly documented.
- [ ] The CI passes (`R CMD check`, linter, unit tests, spelling).
- [ ] Any generated files have been updated (e.g. `.Rd` files with `roxygen2::roxygenise()`)

2024-05-17 14:29 UTC, jakubnowicki requested changes
Please check my comments. Also, please add [the CI configuration for `pkgdown`](https://github.com/Appsilon/reactable.extras/blob/main/.github/workflows/pkgdown.yml)

2024-05-17 14:29 UTC, jakubnowicki commented on pkgdown/_pkgdown.yml
> +      <script async defer src="https://buttons.github.io/buttons.js"></script>
```suggestion
    in_header: |
    <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-8GE9YEGHF6"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-DVX9BJSBX4');
      </script>
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-FQQZL5V93G"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-FQQZL5V93G');
      </script>
      <script async defer src="https://buttons.github.io/buttons.js"></script>
```

2024-05-17 14:29 UTC, jakubnowicki commented on pkgdown/_pkgdown.yml
> +  structure:
```suggestion
navbar:
  type: light
  structure:
```

2024-05-17 14:29 UTC, jakubnowicki commented on pkgdown/extra.css
> +.navbar-dark .navbar-nav .active > .nav-link {
```suggestion
.navbar-light .navbar-nav .active > .nav-link {
```

2024-05-17 14:29 UTC, jakubnowicki commented on pkgdown/extra.css
> +
```suggestion
```
Input search style is fixed by `type: light` in `_pkgdown.yml`

2024-05-20 06:33 UTC, radbasa commented
> Please check my comments. Also, please add [the CI configuration for `pkgdown`](https://github.com/Appsilon/reactable.extras/blob/main/.github/workflows/pkgdown.yml)

Used `pkgdown.yaml` CI from `usethis::use_github_actions("pkgdown")`

2024-05-20 13:25 UTC, jakubnowicki approved these changes
LGTM

2024-05-21 03:17 UTC, merged